services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"   # внешний порт 80 на порт 80 контейнера nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

  api:
    build: .
    expose:
      - "8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pg_data:
