name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.11 (локально для тестов и линтов)
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Deploy to server with docker-compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            # Папка проекта
            PROJECT_DIR=/var/www/clinic_appointments

            mkdir -p $PROJECT_DIR
            cd $PROJECT_DIR

            # Записываем .env из секретов GitHub (внимание! отступы убраны)
            cat > .env <<EOF
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_PORT=${{ secrets.DB_PORT }}
            EOF

            # Обновляем или клонируем репозиторий
            if [ -d ".git" ]; then
              echo "Updating existing repo"
              git fetch origin
              git reset --hard origin/main
            else
              echo "Cloning repo"
              git clone https://github.com/kukarek/clinic_appointments.git .
            fi

            # Собираем и запускаем контейнеры
            docker-compose pull
            docker-compose build
            docker-compose up -d --force-recreate

            # Запускаем тесты и показываем покрытие
            docker-compose run --rm api pytest --cov=app --cov-report=term-missing


